client/Models/CartViewModel.cs
using System.Collections.Generic;
using ViewModelShare.CartOrder;

namespace client.Models
{
    public class CartViewModel
    {
        public int Total { get; set; }
        public int Count { get; set; }
        public IEnumerable<CartOrderRespone> Orders { get; set; }
    }
}

client/Models/ErrorViewModel.cs
using System;

namespace client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

client/Models/HeaderViewModel.cs
using System.Collections.Generic;
using ViewModelShare.Category;

namespace client.Models
{
    public class HeaderViewModel
    {
        public IEnumerable<CategoryRespone> Categories { get; set; }
        public string UserName { get; set; }
    }
}

client/Controllers/AuthController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace client.Controllers
{
    public class AuthController : Controller
    {

        [HttpGet("/logout")]
        public IActionResult Logout()
        {
            return SignOut("Cookies", "oidc");
        }

        [HttpGet("/login")]
        public async Task login()
        {
            await HttpContext.ChallengeAsync(new AuthenticationProperties { RedirectUri = "/" });
        }
    }
}

client/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using client.Models;
using client.Services;
using System.Collections.Generic;
using ViewModelShare.Category;

namespace client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHttpClientService _client;

        public HomeController(ILogger<HomeController> logger,
            IHttpClientService client)
        {
            _logger = logger;
            _client = client;
        }

        public async Task<ActionResult<IEnumerable<CategoryRespone>>> Index()
        {
            var categories = await _client.GetCategories();

            return View(categories);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

client/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using client.Constants;
using client.Models;
using client.Services;
using client.Services.Cart;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ViewModelShare.CartOrder;
using ViewModelShare.Product;

namespace client.Controllers
{
    public class OrderController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IHttpClientService _client;

        public OrderController(IHttpClientService client,
            ICartService cartService)
        {
            _cartService = cartService;
            _client = client;
        }

        public async Task<ActionResult<CartViewModel>> Index()
        {
            var cartVM = await _cartService.GetCartViewModel();

            return View(cartVM);
        }

        [HttpPost("[controller]/{productId}")]
        public async Task<ActionResult<IEnumerable<CartOrderRequest>>> AddProduct(
            int productId, int quantity, ProductRespone product)
        {
            var cartOrder = new CartOrderRespone
            {
                Product = product,
                Quantity = quantity
            };

            var orders = await _cartService.AddOrder(cartOrder);

            return Ok(orders);
        }

        public async Task<ActionResult<IEnumerable<CartOrderRequest>>> Remove(int productId)
        {
            await _cartService.Remove(productId);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost("[controller]")]
        public async Task<IActionResult> CreateOrder()
        {
            var result = await _client.Order();

            if (result is null)
            {
                return View("OrderResult", false);
            }

            await _cartService.Clear();

            return View("OrderResult", true);
        }
    }
}

client/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using client.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ViewModelShare.Product;

namespace client.Controllers
{
    public class ProductController : Controller
    {
        private IHttpClientService _client;

        public ProductController(IHttpClientService client)
        {
            _client = client;
        }

        [HttpGet("[controller]/{id}")]
        public async Task<ActionResult<ProductRespone>> Detail(int id)
        {
            var product = await _client.GetProductById(id);

            return View(product);
        }

        public async Task<ActionResult<IEnumerable<ProductRespone>>> Index(int? categoryId)
        {
            IEnumerable<ProductRespone> products;

            if (categoryId is null)
            {
                products = await _client.GetProducts();
            }
            else
            {
                products = await _client.GetProductsByCategory(categoryId.Value);
            }


            return View(products);
        }

        [Authorize]
        [HttpPost("[controller]/{id}")]
        public async Task<IActionResult> Voting(int id, int rating)
        {
            var result = await _client.Voting(id, rating);

            if (result is false)
            {
                return Content("false");
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

client/ViewComponents/CartItemViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ViewModelShare.CartOrder;

namespace client.ViewComponents
{
    [ViewComponent(Name = "CartItem")]
    public class CartItemViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(CartOrderRespone cartOrder)
        {
            return await Task.FromResult(View("Default", cartOrder));
        }
    }
}

client/ViewComponents/CartViewComponent.cs
using System.Threading.Tasks;
using client.Services.Cart;
using Microsoft.AspNetCore.Mvc;

namespace client.ViewComponents
{
    [ViewComponent(Name = "Cart")]
    public class CartViewComponent : ViewComponent
    {
        private readonly ICartService _cartService;

        public CartViewComponent(ICartService cartService)
        {
            _cartService = cartService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cartVM = await _cartService.GetCartViewModel();

            return View("Default", cartVM);
        }
    }
}

client/ViewComponents/HeaderViewComponent.cs
using System.Security.Claims;
using System.Threading.Tasks;
using client.Models;
using client.Services;
using Microsoft.AspNetCore.Mvc;

namespace client.ViewComponents
{
    [ViewComponent(Name = "Header")]
    public class HeaderViewComponent : ViewComponent
    {
        private IHttpClientService _client;

        public HeaderViewComponent(IHttpClientService client)
        {
            _client = client;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var name = "";
            if (User.Identity.IsAuthenticated)
            {
                // var claimsIdentity = User.Identity as ClaimsIdentity;
                // name = claimsIdentity.FindFirst("name").Value.ToString();
                name = User.Identity.Name;
            }

            var categories = await _client.GetCategories();

            var headerVM = new HeaderViewModel
            {
                Categories = categories,
                UserName = name,
            };

            return View("Default", headerVM);
        }
    }
}

client/ViewComponents/ProductViewComponent.cs
using System.Security.Claims;
using System.Threading.Tasks;
using client.Models;
using client.Services;
using Microsoft.AspNetCore.Mvc;
using ViewModelShare.Product;

namespace client.ViewComponents
{
    [ViewComponent(Name = "Product")]
    public class ProductViewComponent : ViewComponent
    {
        private IHttpClientService _client;

        public ProductViewComponent(IHttpClientService client)
        {
            _client = client;
        }
        public async Task<IViewComponentResult> InvokeAsync(ProductRespone product)
        {
            return await Task.FromResult(View("Default", product));
        }
    }
}

client/Views/Order/Index.cshtml
@model CartViewModel

@{
    ViewData["Title"] = "Cart";
}

<section class="container" style="min-height: 80vh;">
    @if (Model.Count.Equals(0))
    {
        <div>Your Cart is empty</div>
    }
    else
    {
        <!--Grid row-->
        <div class="row">

            <!--Grid column-->
            <div class="col-lg-8">

                <div class="card wish-list mb-3">
                    <div class="card-body">

                        <h5 class="mb-4">Cart (<span>@Model.Count</span> items)</h5>

                        @foreach (var order in Model.Orders)
                        {
                            @await Component.InvokeAsync("CartItem", order)
                        }

                    </div>
                </div>
                <!-- Card -->

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4">
                <!-- Card -->
                <div class="mb-3">
                    <div class="pt-4">

                        <h5 class="mb-3">The total amount</h5>

                        <ul class="list-group list-group-flush">
                            <li
                                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                                Temporary amount
                                <span>$@Model.Total</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                Shipping
                                <span>FREE</span>
                            </li>
                            <li
                                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                                <div>
                                    <strong>The total amount of</strong>
                                    <strong>
                                        <p class="mb-0">(including VAT)</p>
                                    </strong>
                                </div>
                                <span><strong>$@Model.Total</strong></span>
                            </li>
                        </ul>

                        <form action="~/order" method="POST">
                            <button type="submit" class="btn btn-primary btn-block">Checkout!</button>
                        </form>

                    </div>
                </div>
                <!-- Card -->
            </div>
            <!--Grid column-->
        </div>
        <!-- Grid row -->
    }
</section>

client/Views/Order/OrderResult.cshtml
@model bool

@{
    ViewData["Title"] = "Order";
}

<div class="container text-center mt-5" style="min-height: 80vh;">
    @if (Model)
    {
        <h1 class="text-success">Your Order Successful</h1>
    }
    else
    {
        <h1 class="text-danger">Your Order Was Failed Please Try again or comeback again</h1>
    }
</div>

client/Views/Product/Detail.cshtml
@model ProductRespone

@{
    ViewData["Title"] = Model.Name;
}

<section class="breadcrumbs">
    <div class="container">

        <div class="d-flex justify-content-between align-items-center">
            <h2>@Model.Name</h2>
            <ol>
                <li>
                    <a href="~/#">Home</a>
                </li>
                <li>
                    <a href="~/product/?categoryId=@Model.CategoryId">@Model.CategoryName</a>
                </li>
                <li>@Model.Name</li>
            </ol>
        </div>

    </div>
</section>

<section class="portfolio-details">
    <div class="container">

        <div class="portfolio-details-container">

            <div class="owl-carousel portfolio-details-carousel">
                <img src="@Model.Image" class="img-fluid" alt="@Model.Name">
            </div>

            <div class="portfolio-info">
                <h3>@Model.Name</h3>
                <ul>
                    <li><strong>Category</strong>: @Model.CategoryName</li>
                    <li><strong>Price</strong>: $ @Model.Price</li>
                    <li><strong>Rated</strong>: @Model.Rated</li>
                    <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
                    <li>
                        @for (int i = 1; i < 6; i++)
                        {
                            if (i <= Model.Rated)
                            {
                                <span class="fa fa-star checked"></span>
                            }
                            else
                            {
                                <span class="fa fa-star"></span>
                            }
                        }
                    </li>

                    <form action="~/product/@Model.ProductId" method="POST">
                        <ul class="rate-area">
                            <input type="submit" id="5-star" name="rating" value="5" /><label for="5-star"
                                title="Amazing">5
                                stars</label>
                            <input type="submit" id="4-star" name="rating" value="4" /><label for="4-star"
                                title="Good">4
                                stars</label>
                            <input type="submit" id="3-star" name="rating" value="3" /><label for="3-star"
                                title="Average">3
                                stars</label>
                            <input type="submit" id="2-star" name="rating" value="2" /><label for="2-star"
                                title="Not Good">2
                                stars</label>
                            <input type="submit" id="1-star" name="rating" value="1" /><label for="1-star" title="Bad">1
                                star</label>
                        </ul>
                    </form>

                    <form id="buy" method="POST">
                        <input type="hidden" name="productId" value="@Model.ProductId" />
                        <input type="hidden" name="name" value="@Model.Name" />
                        <input type="hidden" name="price" value="@Model.Price" />
                        <input type="hidden" name="image" value="@Model.Image" />
                        <input type="hidden" name="description" value="@Model.Description" />
                        <input type="hidden" name="rated" value="@Model.Rated" />
                        <input type="hidden" name="categoryname" value="@Model.CategoryName" />

                        <div class="number-input md-number-input">
                            <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()"
                                class="btn btn-primary" type="button">
                                -
                            </button>
                            <input class="quantity" min="0" name="quantity" value="1" type="number">

                            <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()"
                                class="btn btn-primary" type="button">
                                +
                            </button>
                        </div>

                        <div class="d-flex mt-3">
                            <button type="submit" class="btn btn-outline-primary mx-auto">
                                Add to Cart
                            </button>
                        </div>
                    </form>
                </ul>
            </div>

        </div>

        <div class="portfolio-description">
            <h2>@Model.Name</h2>
            <p>@Model.Description</p>
        </div>
    </div>
</section><!-- End Portfolio Details Section -->

client/Views/Product/Index.cshtml
@model List<ProductRespone>

@{
    ViewData["Title"] = "Category";
}

<section id="portfolio" class="portfolio wow fadeInUp" style="min-height: 80vh;">
    <div class="container">
        <div class="container section-header">
            <h2>Our Portfolio</h2>
            <p>Sed tamen tempor magna labore dolore dolor sint tempor duis magna elit veniam aliqua esse amet
                veniam enim export quid quid veniam aliqua eram noster malis nulla duis fugiat culpa esse aute
                nulla ipsum velit export irure minim illum fore</p>
        </div>

        <div class="row portfolio-container">

            @foreach (var product in Model)
            {
                <div class="col-lg-4 col-md-6 portfolio-item">
                    @await Component.InvokeAsync("Product", product)
                </div>
            }

        </div>

    </div>
</section>

client/Views/Shared/Components/Cart/Default.cshtml
@model CartViewModel

<a href="~/order" class="cart">
    <div id="cart_total" class="mr-1">
        @if (!Model.Count.Equals(0))
        {
            <div>@Model.Count<span> - @Model.Total $</span></div>
        }
    </div>
    <i class="fa fa-shopping-cart pt-1"></i>
</a>

client/Views/Shared/Components/Product/Default.cshtml
@model ProductRespone

<a href="~/product/@Model.ProductId">
    <img src="@Model.Image" class="img-fluid" alt="">
</a>
<div class="portfolio-info">
    <h4>@Model.Name</h4>
    <p>$ @Model.Price</p>

    <div class="rating">
        @for (int i = 5; i >= 1; i--)
        {
            if (i <= Model.Rated)
            {
                <span class="fa fa-star checked" data-value="@i" data-id="@Model.ProductId"></span>
            }
            else
            {
                <span class="fa fa-star" data-value="@i" data-id="@Model.ProductId"></span>
            }
        }
    </div>
    <a href="@Model.Image" data-gall="portfolioGallery" class="venobox preview-link" title="@Model.Name">
        <i class="bx bx-plus"></i>
    </a>
    <form class="d-flex number-input">
        <input type="hidden" name="productId" value="@Model.ProductId" />
        <input type="hidden" name="name" value="@Model.Name" />
        <input type="hidden" name="price" value="@Model.Price" />
        <input type="hidden" name="image" value="@Model.Image" />
        <input type="hidden" name="description" value="@Model.Description" />
        <input type="hidden" name="rated" value="@Model.Rated" />
        <input type="hidden" name="categoryname" value="@Model.CategoryName" />

        <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="btn btn-cart"
            type="button">
            <i class="bx bx-minus"></i>
        </button>
        <input class="quantity text-center" min="0" name="quantity" value="1" type="number">

        <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="btn btn-cart"
            type="button">
            <i class="bx bx-plus"></i>
        </button>

        <input id="add-to-cart" class="btn mx-auto addtocart" type="submit" Value="Add to Cart" />
    </form>
</div>